# This configuration is overwritten in a configmap for the deployment.
# Make sure to check the clowdapp.yaml if you want to make any change in
# stage or prod.

"host": "0.0.0.0"
"port": 8000
"logging":
   "version": 1
   "disable_existing_loggers": false
   "formatters":
      "KeyValueFormatter":
         "format": "timestamp=%(asctime)s pid=%(process)d loglevel=%(levelname)s msg=%(message)s"
   "handlers":
      "console":
         "level": "DEBUG"
         "class": "logging.StreamHandler"
         "formatter": "KeyValueFormatter"
   "loggers":
      "gunicorn.access":
         "propagate": true
      "gunicorn.error":
         "propagate": true
   "root":
      "level": "DEBUG"
      "handlers": ["console"]
