version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  default:
    (): uvicorn.logging.DefaultFormatter
    fmt: '%(asctime)s %(levelprefix)s %(message)s'
    use_colors: None
  access:
    (): uvicorn.logging.AccessFormatter
    fmt: '%(asctime)s %(levelprefix)s %(client_addr)s - "%(request_line)s" %(status_code)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stderr
loggers:
  insights_content_template_renderer:
    level: DEBUG
    handlers: [default]
    propagate: no
  uvicorn:
    handlers: [default]
    level: INFO
    propagate: no
  uvicorn.error:
    level: INFO
root:
  level: INFO
  handlers: [default]
